export const DEMO_RECOMMENDATIONS = [
  {
    rank: 1,
    name: "Mancozeb 75% WP",
    category: "fungicide",
    legal_status: "approved",
    concentration_pct: 75,
    dose_per_acre: "400g",
    dose_per_litre: "2.5g/L",
    dilution_litres_per_acre: 200,
    application_method: "2.5g ని 1 లీటర్ నీటిలో కలపండి. ఆకుల రెండు వైపులా spray చేయండి.",
    interval_days: 7,
    estimated_cost_per_acre_inr: 90,
    total_score: 78.5,
    weather_advisory: "వర్షం లేని సమయంలో spray చేయండి.",
    available_at: "APCOB Madanapalle, Krishna Agro, Sai Agri Inputs",
    effect_days: { start: 2, peak: 7 },
    reason: "తక్కువ ఖర్చు, స్థానికంగా దొరుకుతుంది"
  },
  {
    rank: 2,
    name: "Carbendazim 50% WP",
    category: "fungicide",
    legal_status: "approved",
    concentration_pct: 50,
    dose_per_acre: "200g",
    dose_per_litre: "1g/L",
    dilution_litres_per_acre: 200,
    application_method: "1g ని 1 లీటర్ నీటిలో కలపండి. Systemic — వర్షంలో కూడా పని చేస్తుంది.",
    interval_days: 10,
    estimated_cost_per_acre_inr: 55,
    total_score: 74.0,
    weather_advisory: "వర్షంలో కూడా ప్రభావవంతంగా ఉంటుంది.",
    available_at: "APCOB Madanapalle, RythuBazaar",
    effect_days: { start: 2, peak: 5 },
    reason: "Systemic — లోపల నుండి పని చేస్తుంది"
  }
];

export const MANDAL_COORDS: Record<string, { lat: number; lon: number; div: string }> = {
  "Madanapalle": { lat: 13.5504, lon: 78.5012, div: "Madanapalle" },
  "B.Kothakota": { lat: 13.582, lon: 78.476, div: "Madanapalle" },
  "Mulakala Cheruvu": { lat: 13.61, lon: 78.44, div: "Madanapalle" },
  "Pedda Thippa Samudram": { lat: 13.64, lon: 78.39, div: "Madanapalle" },
  "Thamballapalle": { lat: 13.845, lon: 78.36, div: "Madanapalle" },
  "Pedda Mandyam": { lat: 13.72, lon: 78.48, div: "Madanapalle" },
  "Kurabala Kota": { lat: 13.62, lon: 78.55, div: "Madanapalle" },
  "Valmikipuram": { lat: 13.56, lon: 78.63, div: "Madanapalle" },
  "Nimmanapalle": { lat: 13.51, lon: 78.6, div: "Madanapalle" },
  "Ramasamudram": { lat: 13.45, lon: 78.52, div: "Madanapalle" },
  "Kalikiri": { lat: 13.65, lon: 78.78, div: "Madanapalle" },
  "Pileru": { lat: 13.654, lon: 79.12, div: "Madanapalle" },
  "Vayalpadu": { lat: 13.876, lon: 78.64, div: "Madanapalle" },
  "Gudipala": { lat: 13.48, lon: 78.45, div: "Madanapalle" },
  "Rayachoti": { lat: 14.055, lon: 78.751, div: "Rayachoti" },
  "Galiveedu": { lat: 13.98, lon: 78.66, div: "Rayachoti" },
  "Lakkireddi Palle": { lat: 14.1, lon: 78.72, div: "Rayachoti" },
  "Ramapuram": { lat: 14.12, lon: 78.79, div: "Rayachoti" },
  "Chinna Mandem": { lat: 14.0, lon: 78.78, div: "Rayachoti" },
  "Sambepalle": { lat: 14.02, lon: 78.85, div: "Rayachoti" },
  "Gurramkonda": { lat: 13.78, lon: 78.85, div: "Rayachoti" },
  "Kalakada": { lat: 13.87, lon: 78.92, div: "Rayachoti" },
  "Kambhamvaripalle": { lat: 13.92, lon: 79.0, div: "Rayachoti" },
  "Tsundupalle": { lat: 14.08, lon: 78.95, div: "Rayachoti" },
  "Rajampeta": { lat: 14.1935, lon: 79.1571, div: "Rajampeta" },
  "Nandalur": { lat: 14.35, lon: 79.08, div: "Rajampeta" },
  "Penagalur": { lat: 14.28, lon: 79.25, div: "Rajampeta" },
  "Chitvel": { lat: 14.17, lon: 79.32, div: "Rajampeta" },
  "Pullampeta": { lat: 14.1, lon: 79.2, div: "Rajampeta" },
  "Obulavaripalle": { lat: 14.16, lon: 79.37, div: "Rajampeta" },
  "Kodur": { lat: 14.1, lon: 79.42, div: "Rajampeta" },
  "Veeraballe": { lat: 14.13, lon: 79.05, div: "Rajampeta" },
  "Punganur": { lat: 13.368, lon: 78.573, div: "Chittoor" },
  "Palamaner": { lat: 13.203, lon: 78.745, div: "Chittoor" },
  "Chittoor": { lat: 13.2172, lon: 79.1003, div: "Chittoor" },
  "Kuppam": { lat: 12.748, lon: 78.322, div: "Chittoor" },
  "Bangarupalem": { lat: 13.16, lon: 79.04, div: "Chittoor" },
  "Santhipuram": { lat: 13.28, lon: 78.66, div: "Chittoor" }
};

export const DISEASE_PREVALENCE: Record<string, Record<string, number>> = {
  "Madanapalle": { "Early Blight": 72, "Late Blight": 45, "TYLCV": 35, "Septoria Leaf Spot": 28, "Powdery Mildew": 15 },
  "B.Kothakota": { "Early Blight": 68, "Late Blight": 42, "TYLCV": 30, "Septoria Leaf Spot": 25 },
  "Mulakala Cheruvu": { "Early Blight": 65, "Late Blight": 40, "TYLCV": 28 },
  "Pedda Thippa Samudram": { "Early Blight": 60, "Late Blight": 38, "TYLCV": 25 },
  "Thamballapalle": { "Early Blight": 62, "Late Blight": 44, "TYLCV": 32 },
  "Pedda Mandyam": { "Early Blight": 66, "Late Blight": 41, "TYLCV": 29 },
  "Kurabala Kota": { "Early Blight": 64, "Late Blight": 40, "TYLCV": 27 },
  "Valmikipuram": { "Early Blight": 70, "Late Blight": 43, "TYLCV": 33, "Septoria Leaf Spot": 22 },
  "Nimmanapalle": { "Early Blight": 68, "Late Blight": 42, "TYLCV": 30 },
  "Ramasamudram": { "Early Blight": 63, "Late Blight": 39, "TYLCV": 26 },
  "Kalikiri": { "Early Blight": 65, "Late Blight": 38, "TYLCV": 40, "Septoria Leaf Spot": 32 },
  "Pileru": { "Early Blight": 60, "Late Blight": 35, "TYLCV": 38 },
  "Vayalpadu": { "Early Blight": 58, "Late Blight": 36, "TYLCV": 28 },
  "Gudipala": { "Early Blight": 67, "Late Blight": 43, "TYLCV": 31 },
  "Rayachoti": { "Early Blight": 55, "Late Blight": 30, "TYLCV": 25, "Powdery Mildew": 20 },
  "Galiveedu": { "Early Blight": 52, "Late Blight": 28, "TYLCV": 22 },
  "Lakkireddi Palle": { "Early Blight": 54, "Late Blight": 29, "TYLCV": 24 },
  "Ramapuram": { "Early Blight": 50, "Late Blight": 27, "TYLCV": 20 },
  "Chinna Mandem": { "Early Blight": 53, "Late Blight": 30, "TYLCV": 23 },
  "Sambepalle": { "Early Blight": 51, "Late Blight": 28, "TYLCV": 21 },
  "Gurramkonda": { "Early Blight": 56, "Late Blight": 32, "TYLCV": 26 },
  "Kalakada": { "Early Blight": 57, "Late Blight": 33, "TYLCV": 27 },
  "Kambhamvaripalle": { "Early Blight": 55, "Late Blight": 31, "TYLCV": 25 },
  "Tsundupalle": { "Early Blight": 50, "Late Blight": 26, "TYLCV": 20 },
  "Rajampeta": { "Early Blight": 48, "Late Blight": 25, "TYLCV": 18 },
  "Nandalur": { "Early Blight": 45, "Late Blight": 23, "TYLCV": 16 },
  "Penagalur": { "Early Blight": 46, "Late Blight": 24, "TYLCV": 17 },
  "Chitvel": { "Early Blight": 44, "Late Blight": 22, "TYLCV": 15 },
  "Pullampeta": { "Early Blight": 47, "Late Blight": 24, "TYLCV": 18 },
  "Obulavaripalle": { "Early Blight": 45, "Late Blight": 23, "TYLCV": 16 },
  "Kodur": { "Early Blight": 43, "Late Blight": 21, "TYLCV": 15 },
  "Veeraballe": { "Early Blight": 46, "Late Blight": 24, "TYLCV": 17 },
  "Punganur": { "Early Blight": 65, "Late Blight": 50, "TYLCV": 40, "Septoria Leaf Spot": 32 },
  "Palamaner": { "Early Blight": 55, "Late Blight": 42, "TYLCV": 28 },
  "Chittoor": { "Early Blight": 58, "Late Blight": 38, "TYLCV": 30 },
  "Kuppam": { "Early Blight": 50, "Late Blight": 35, "TYLCV": 25 }
};

export const FALLBACK_PESTICIDES = [
  { id: "F_INDOFIL_M45", trade_name: "Indofil M-45", active_ingredient: "Mancozeb 75% WP", category: "fungicide", diseases: ["Early Blight", "Late Blight", "Leaf Spot"], pack_size: "1kg", exact_pack_price_inr: 400, cost_per_acre_inr: 150, dosage_per_liter: "2.5 g/L", locally_available: true },
  { id: "F_SAAF", trade_name: "UPL Saaf", active_ingredient: "Carbendazim 12% + Mancozeb 63% WP", category: "fungicide", diseases: ["Early Blight", "Late Blight"], pack_size: "500g", exact_pack_price_inr: 500, cost_per_acre_inr: 375, dosage_per_liter: "2.5 g/L", locally_available: true },
  { id: "F_AMISTAR_1", trade_name: "Amistar", active_ingredient: "Azoxystrobin 23% SC", category: "fungicide", diseases: ["Early Blight", "Powdery Mildew"], pack_size: "100ml", exact_pack_price_inr: 705, cost_per_acre_inr: 1057, dosage_per_liter: "1 ml/L", locally_available: true },
  { id: "F_RIDOMIL_GOLD", trade_name: "Ridomil Gold", active_ingredient: "Metalaxyl 8% + Mancozeb 64% WP", category: "fungicide", diseases: ["Late Blight"], pack_size: "100g", exact_pack_price_inr: 228, cost_per_acre_inr: 342, dosage_per_liter: "1.5 g/L", locally_available: true },
  { id: "F_BAVISTIN", trade_name: "Bavistin", active_ingredient: "Carbendazim 50% WP", category: "fungicide", diseases: ["Fusarium Wilt", "Early Blight"], pack_size: "500g", exact_pack_price_inr: 569, cost_per_acre_inr: 170, dosage_per_liter: "1 g/L", locally_available: true },
  { id: "F_BLITOX", trade_name: "Blitox", active_ingredient: "Copper Oxychloride 50% WP", category: "fungicide", diseases: ["Septoria Leaf Spot", "Bacterial Spot"], pack_size: "500g", exact_pack_price_inr: 581, cost_per_acre_inr: 435, dosage_per_liter: "2.5 g/L", locally_available: true },
  { id: "F_SULFEX", trade_name: "Sulfex", active_ingredient: "Wettable Sulphur 80% WP", category: "fungicide", diseases: ["Powdery Mildew"], pack_size: "500g", exact_pack_price_inr: 180, cost_per_acre_inr: 135, dosage_per_liter: "2.5 g/L", locally_available: true },
  { id: "F_KAVACH", trade_name: "Kavach", active_ingredient: "Chlorothalonil 75% WP", category: "fungicide", diseases: ["Early Blight", "Late Blight"], pack_size: "500g", exact_pack_price_inr: 650, cost_per_acre_inr: 390, dosage_per_liter: "2 g/L", locally_available: true },
  { id: "F_NATIVO", trade_name: "Nativo", active_ingredient: "Tebuconazole 50% + Trifloxystrobin 25% WG", category: "fungicide", diseases: ["Early Blight", "Powdery Mildew"], pack_size: "100g", exact_pack_price_inr: 850, cost_per_acre_inr: 850, dosage_per_liter: "0.5 g/L", locally_available: false },
  { id: "F_SCORE", trade_name: "Score", active_ingredient: "Difenoconazole 25% EC", category: "fungicide", diseases: ["Early Blight"], pack_size: "250ml", exact_pack_price_inr: 550, cost_per_acre_inr: 330, dosage_per_liter: "0.5 ml/L", locally_available: true },
  { id: "F_ANTRACOL", trade_name: "Antracol", active_ingredient: "Propineb 70% WP", category: "fungicide", diseases: ["Early Blight", "Buckeye Rot"], pack_size: "500g", exact_pack_price_inr: 420, cost_per_acre_inr: 250, dosage_per_liter: "3 g/L", locally_available: true },
  { id: "F_CURZATE", trade_name: "Curzate M8", active_ingredient: "Cymoxanil 8% + Mancozeb 64% WP", category: "fungicide", diseases: ["Late Blight"], pack_size: "500g", exact_pack_price_inr: 680, cost_per_acre_inr: 408, dosage_per_liter: "3 g/L", locally_available: true },
  { id: "F_ACROBAT", trade_name: "Acrobat", active_ingredient: "Dimethomorph 50% WP", category: "fungicide", diseases: ["Late Blight"], pack_size: "200g", exact_pack_price_inr: 750, cost_per_acre_inr: 560, dosage_per_liter: "1.5 g/L", locally_available: true },
  { id: "F_ERANTHIS", trade_name: "Eranthis", active_ingredient: "Kresoxim-methyl 44.3% SC", category: "fungicide", diseases: ["Early Blight"], pack_size: "250ml", exact_pack_price_inr: 1100, cost_per_acre_inr: 660, dosage_per_liter: "1 ml/L", locally_available: false },
  { id: "F_ROKO", trade_name: "Roko", active_ingredient: "Thiophanate Methyl 70% WP", category: "fungicide", diseases: ["Fusarium Wilt", "Powdery Mildew"], pack_size: "250g", exact_pack_price_inr: 320, cost_per_acre_inr: 192, dosage_per_liter: "1 g/L", locally_available: true },
  { id: "F_VALIDA", trade_name: "Sheathmar", active_ingredient: "Validamycin 3% L", category: "fungicide", diseases: ["Rhizoctonia Root Rot"], pack_size: "500ml", exact_pack_price_inr: 350, cost_per_acre_inr: 210, dosage_per_liter: "2 ml/L", locally_available: true },
  { id: "F_KOSU", trade_name: "Kasu-B", active_ingredient: "Kasugamycin 3% SL", category: "fungicide", diseases: ["Bacterial Leaf Spot"], pack_size: "500ml", exact_pack_price_inr: 400, cost_per_acre_inr: 240, dosage_per_liter: "2 ml/L", locally_available: true },
  { id: "F_KOCIDE", trade_name: "Kocide 2000", active_ingredient: "Copper Hydroxide 53.8% DF", category: "fungicide", diseases: ["Early Blight", "Bacterial Spot"], pack_size: "500g", exact_pack_price_inr: 750, cost_per_acre_inr: 450, dosage_per_liter: "2 g/L", locally_available: true },
  { id: "F_CAPTAF", trade_name: "Captaf", active_ingredient: "Captan 50% WP", category: "fungicide", diseases: ["Damping off", "Early Blight"], pack_size: "500g", exact_pack_price_inr: 450, cost_per_acre_inr: 270, dosage_per_liter: "2.5 g/L", locally_available: true },
  { id: "F_HEXA", trade_name: "Hexaconazole 5% SC", active_ingredient: "Hexaconazole 5% SC", category: "fungicide", diseases: ["Powdery Mildew"], pack_size: "500ml", exact_pack_price_inr: 280, cost_per_acre_inr: 168, dosage_per_liter: "2 ml/L", locally_available: true },
  { id: "I_ACTARA", trade_name: "Actara", active_ingredient: "Thiamethoxam 25% WG", category: "insecticide", diseases: ["Whitefly", "Aphids"], pack_size: "100g", exact_pack_price_inr: 280, cost_per_acre_inr: 140, dosage_per_liter: "0.5 g/L", locally_available: true },
  { id: "I_CONFIDOR", trade_name: "Confidor", active_ingredient: "Imidacloprid 17.8% SL", category: "insecticide", diseases: ["Whitefly", "Jassids"], pack_size: "100ml", exact_pack_price_inr: 410, cost_per_acre_inr: 300, dosage_per_liter: "0.5 ml/L", locally_available: true },
  { id: "I_PRIDE", trade_name: "Pride", active_ingredient: "Acetamiprid 20% SP", category: "insecticide", diseases: ["Whitefly"], pack_size: "100g", exact_pack_price_inr: 250, cost_per_acre_inr: 125, dosage_per_liter: "0.5 g/L", locally_available: true },
  { id: "I_PEGASUS", trade_name: "Pegasus", active_ingredient: "Diafenthiuron 50% WP", category: "insecticide", diseases: ["Whitefly", "Mites"], pack_size: "250g", exact_pack_price_inr: 650, cost_per_acre_inr: 520, dosage_per_liter: "1.5 g/L", locally_available: true },
  { id: "I_TRACER", trade_name: "Tracer", active_ingredient: "Spinosad 45% SC", category: "insecticide", diseases: ["Fruit Borer", "Thrips"], pack_size: "75ml", exact_pack_price_inr: 1450, cost_per_acre_inr: 1450, dosage_per_liter: "0.3 ml/L", locally_available: false },
  { id: "I_PROCLAIM", trade_name: "Proclaim", active_ingredient: "Emamectin Benzoate 5% SG", category: "insecticide", diseases: ["Fruit Borer"], pack_size: "100g", exact_pack_price_inr: 550, cost_per_acre_inr: 440, dosage_per_liter: "0.5 g/L", locally_available: true },
  { id: "I_CORAGEN", trade_name: "Coragen", active_ingredient: "Chlorantraniliprole 18.5% SC", category: "insecticide", diseases: ["Fruit Borer"], pack_size: "60ml", exact_pack_price_inr: 1150, cost_per_acre_inr: 1150, dosage_per_liter: "0.4 ml/L", locally_available: true },
  { id: "I_FAME", trade_name: "Fame", active_ingredient: "Flubendiamide 39.35% SC", category: "insecticide", diseases: ["Fruit Borer"], pack_size: "50ml", exact_pack_price_inr: 850, cost_per_acre_inr: 850, dosage_per_liter: "0.3 ml/L", locally_available: true },
  { id: "I_REGENT", trade_name: "Regent 5% SC", active_ingredient: "Fipronil 5% SC", category: "insecticide", diseases: ["Thrips", "Aphids"], pack_size: "250ml", exact_pack_price_inr: 350, cost_per_acre_inr: 280, dosage_per_liter: "2 ml/L", locally_available: true },
  { id: "I_REMON", trade_name: "Remon", active_ingredient: "Novaluron 10% EC", category: "insecticide", diseases: ["Fruit Borer"], pack_size: "250ml", exact_pack_price_inr: 650, cost_per_acre_inr: 520, dosage_per_liter: "1.5 ml/L", locally_available: true },
  { id: "I_AVANT", trade_name: "Avaunt", active_ingredient: "Indoxacarb 14.5% SC", category: "insecticide", diseases: ["Fruit Borer"], pack_size: "100ml", exact_pack_price_inr: 680, cost_per_acre_inr: 544, dosage_per_liter: "1 ml/L", locally_available: true },
  { id: "I_ABACIN", trade_name: "Abacin", active_ingredient: "Abamectin 1.9% EC", category: "insecticide", diseases: ["Red Spider Mite"], pack_size: "100ml", exact_pack_price_inr: 450, cost_per_acre_inr: 360, dosage_per_liter: "1 ml/L", locally_available: true },
  { id: "I_OBERON", trade_name: "Oberon", active_ingredient: "Spiromesifen 22.9% SC", category: "insecticide", diseases: ["Whitefly", "Mites"], pack_size: "100ml", exact_pack_price_inr: 650, cost_per_acre_inr: 520, dosage_per_liter: "1 ml/L", locally_available: true },
  { id: "I_APPLAUD", trade_name: "Applaud", active_ingredient: "Buprofezin 25% SC", category: "insecticide", diseases: ["Whitefly (Nymphs)"], pack_size: "250ml", exact_pack_price_inr: 480, cost_per_acre_inr: 384, dosage_per_liter: "1.5 ml/L", locally_available: true },
  { id: "I_CURACRON", trade_name: "Curacron", active_ingredient: "Profenofos 50% EC", category: "insecticide", diseases: ["Fruit Borer", "Whitefly"], pack_size: "500ml", exact_pack_price_inr: 550, cost_per_acre_inr: 220, dosage_per_liter: "2 ml/L", locally_available: true },
  { id: "I_CYPER", trade_name: "Cyper 25", active_ingredient: "Cypermethrin 25% EC", category: "insecticide", diseases: ["Fruit Borer"], pack_size: "250ml", exact_pack_price_inr: 220, cost_per_acre_inr: 132, dosage_per_liter: "1 ml/L", locally_available: true },
  { id: "I_KARATE", trade_name: "Karate", active_ingredient: "Lambda-cyhalothrin 5% EC", category: "insecticide", diseases: ["Fruit Borer", "Thrips"], pack_size: "250ml", exact_pack_price_inr: 280, cost_per_acre_inr: 168, dosage_per_liter: "1 ml/L", locally_available: true },
  { id: "I_ULALA", trade_name: "Ulala", active_ingredient: "Flonicamid 50% WG", category: "insecticide", diseases: ["Aphids", "Whitefly"], pack_size: "50g", exact_pack_price_inr: 750, cost_per_acre_inr: 900, dosage_per_liter: "0.3 g/L", locally_available: false },
  { id: "B_PLANTOMYCIN", trade_name: "Plantomycin", active_ingredient: "Streptomycin 9% + Tetracycline 1%", category: "bactericide", diseases: ["Bacterial Wilt", "Bacterial Spot"], pack_size: "50g", exact_pack_price_inr: 180, cost_per_acre_inr: 180, dosage_per_liter: "0.2 g/L", locally_available: true },
  { id: "B_BACTNASH", trade_name: "Bactnash", active_ingredient: "2-Bromo-2-Nitropropane", category: "bactericide", diseases: ["Bacterial Leaf Spot"], pack_size: "50g", exact_pack_price_inr: 150, cost_per_acre_inr: 150, dosage_per_liter: "0.3 g/L", locally_available: true }
];
